spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test_database
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl